/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//Designed by Brian Kelly and coded by Brian Kelly & Adam Cahill
package fantasyfootball;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x16114418
 */
public class FantasyFootballGUI_1 extends javax.swing.JFrame {

    private Stats s;
    private ArrayList<Stats> statsinfo;
    private ArrayList<Player> aList;
    private String playername, playerage, playercountry;
    private int count;
    private ArrayList<Details> bList;
    private int counter;
    private String name;
    private String id;
    
    
    /*private Player p;
    private ArrayList<Player> playerinfo;*/
    
    /**
     * Creates new form FantasyFootballGUI
     */
    public FantasyFootballGUI_1() {
        initComponents();
        
        //hide it all
        tfplayername.setVisible(false);
        tfplayerteam.setVisible(false);
        tfpc.setVisible(false);
        cbperformance.setVisible(false);
        cbspeed.setVisible(false);
        cbshotsontarget.setVisible(false);
        btnadd.setVisible(false);
        lblplayerdetails.setVisible(false);
        lblplayername.setVisible(false);
        lblplayerteam.setVisible(false);
        lblplayerscountry.setVisible(false);
        lblperformance.setVisible(false);
        lblspeed.setVisible(false);
        lblstamina.setVisible(false);
        lblshotsontarget.setVisible(false);
        cbstamina.setVisible(false);
        lblplayerstats.setVisible(false);
        playerdetails.setVisible(false);
        adddetailsandstats.setVisible(false);
        enterplayer.setVisible(false);
        pdview.setVisible(false);
        add.setVisible(false);
        redo.setVisible(false);
        btnsave.setVisible(false);
        btnviewsaved.setVisible(false);
        btnlogin.setVisible(false);
        
        
        
        statsinfo = new ArrayList<>();
        
        aList = new ArrayList<>();
        playername = new String();
        playerage = new String();
        playercountry = new String();
        count = 0;
        bList = new ArrayList<>();
        name = new String();
        id = new String();
        counter = 0;
        
        
        
        
        btnview.setVisible(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        stats1 = new fantasyfootball.Stats();
        stats2 = new fantasyfootball.Stats();
        stats3 = new fantasyfootball.Stats();
        lblname = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfid = new javax.swing.JTextField();
        lblplayername = new javax.swing.JLabel();
        lblplayerteam = new javax.swing.JLabel();
        lblplayerscountry = new javax.swing.JLabel();
        tfplayername = new javax.swing.JTextField();
        tfplayerteam = new javax.swing.JTextField();
        tfpc = new javax.swing.JTextField();
        lbluserdetails = new javax.swing.JLabel();
        lblplayerdetails = new javax.swing.JLabel();
        lblplayerstats = new javax.swing.JLabel();
        lblperformance = new javax.swing.JLabel();
        cbperformance = new javax.swing.JComboBox<>();
        lblspeed = new javax.swing.JLabel();
        cbspeed = new javax.swing.JComboBox<>();
        lblstamina = new javax.swing.JLabel();
        cbstamina = new javax.swing.JComboBox<>();
        lblshotsontarget = new javax.swing.JLabel();
        cbshotsontarget = new javax.swing.JComboBox<>();
        playerdetails = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnenter = new javax.swing.JButton();
        enterplayer = new javax.swing.JButton();
        adddetailsandstats = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        add = new javax.swing.JButton();
        pdview = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnviewsaved = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 242, 0));
        lblname.setText("ID");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        lblid.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        lblid.setForeground(new java.awt.Color(255, 242, 0));
        lblid.setText("Name");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        tfname.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        getContentPane().add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 42, 54, -1));

        tfid.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 78, 54, -1));

        lblplayername.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        lblplayername.setForeground(new java.awt.Color(255, 242, 0));
        lblplayername.setText("Player Name");
        getContentPane().add(lblplayername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, -1, -1));

        lblplayerteam.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        lblplayerteam.setForeground(new java.awt.Color(255, 242, 0));
        lblplayerteam.setText("Player Team");
        getContentPane().add(lblplayerteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        lblplayerscountry.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        lblplayerscountry.setForeground(new java.awt.Color(255, 242, 0));
        lblplayerscountry.setText("Players Country");
        getContentPane().add(lblplayerscountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 358, -1, -1));

        tfplayername.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        getContentPane().add(tfplayername, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 279, 45, -1));

        tfplayerteam.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        getContentPane().add(tfplayerteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 317, 45, -1));

        tfpc.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        getContentPane().add(tfpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 355, 45, -1));

        lbluserdetails.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        lbluserdetails.setForeground(new java.awt.Color(255, 242, 0));
        lbluserdetails.setText("User Details");
        getContentPane().add(lbluserdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblplayerdetails.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        lblplayerdetails.setForeground(new java.awt.Color(255, 242, 0));
        lblplayerdetails.setText("Player Details");
        getContentPane().add(lblplayerdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 247, -1, -1));

        lblplayerstats.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        lblplayerstats.setForeground(new java.awt.Color(255, 242, 0));
        lblplayerstats.setText("Player Stats");
        getContentPane().add(lblplayerstats, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 245, -1, -1));

        lblperformance.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        lblperformance.setForeground(new java.awt.Color(255, 242, 0));
        lblperformance.setText("Performance");
        getContentPane().add(lblperformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 280, -1, -1));

        cbperformance.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        cbperformance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Great", "Average", "Bad" }));
        cbperformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbperformanceActionPerformed(evt);
            }
        });
        getContentPane().add(cbperformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 277, -1, -1));

        lblspeed.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        lblspeed.setForeground(new java.awt.Color(255, 242, 0));
        lblspeed.setText("Speed");
        getContentPane().add(lblspeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 312, -1, -1));

        cbspeed.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        cbspeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Great", "Average", "Bad" }));
        cbspeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbspeedActionPerformed(evt);
            }
        });
        getContentPane().add(cbspeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 308, -1, -1));

        lblstamina.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        lblstamina.setForeground(new java.awt.Color(255, 242, 0));
        lblstamina.setText("Stamina");
        getContentPane().add(lblstamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 344, -1, -1));

        cbstamina.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        cbstamina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Great", "Average", "Bad" }));
        cbstamina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstaminaActionPerformed(evt);
            }
        });
        getContentPane().add(cbstamina, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 339, -1, -1));

        lblshotsontarget.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        lblshotsontarget.setForeground(new java.awt.Color(255, 242, 0));
        lblshotsontarget.setText("Shots on target");
        getContentPane().add(lblshotsontarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 376, -1, -1));

        cbshotsontarget.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        cbshotsontarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Great", "Average", "Bad" }));
        cbshotsontarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbshotsontargetActionPerformed(evt);
            }
        });
        getContentPane().add(cbshotsontarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 370, -1, -1));

        playerdetails.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        playerdetails.setText("Enter Football Fantasy Application");
        playerdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(playerdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btnadd.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        btnadd.setText("Enter Player Stats");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 473, -1, -1));

        btnenter.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        btnenter.setText("Enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        enterplayer.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        enterplayer.setText("Enter Player Details");
        enterplayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterplayerActionPerformed(evt);
            }
        });
        getContentPane().add(enterplayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        adddetailsandstats.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        adddetailsandstats.setText("Add ");
        adddetailsandstats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddetailsandstatsActionPerformed(evt);
            }
        });
        getContentPane().add(adddetailsandstats, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 419, -1, -1));

        btnlogout.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        btnlogout.setText("Log out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 10, -1, -1));

        btnview.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        btnview.setText("View Stats");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 419, -1, -1));

        add.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 419, -1, -1));

        pdview.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        pdview.setText("View Details");
        pdview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdviewActionPerformed(evt);
            }
        });
        getContentPane().add(pdview, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 419, -1, -1));

        redo.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        redo.setText("Enter more players");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        getContentPane().add(redo, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 473, -1, -1));

        btnsave.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 473, -1, -1));

        btnviewsaved.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 2, 14)); // NOI18N
        btnviewsaved.setText("View Saved");
        btnviewsaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewsavedActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewsaved, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 473, -1, -1));

        btnlogin.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 14)); // NOI18N
        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 10, 65, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fantasyfootball/BG1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 900, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
        // TODO add your handling code here:
        playerdetails.setVisible(true);
        
       
        name = tfname.getText();
        id = tfid.getText();
        
        Details b = new Details();
        b.setName(name);
        b.setName(id);
        
        bList.add(b);
        
        counter++;
        
        for(int i = 0; i < bList.size();i++){
            JOptionPane.showMessageDialog(null, "Welcome to Fantasy Football "+bList.get(i).getName());
            
        }
        
                
                
        
        
        
        
    }//GEN-LAST:event_btnenterActionPerformed

    private void playerdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerdetailsActionPerformed
        // TODO add your handling code here:
        tfplayername.setVisible(false);
        tfplayerteam.setVisible(false);
        tfpc.setVisible(false);
        cbperformance.setVisible(false);
        cbspeed.setVisible(false);
        cbshotsontarget.setVisible(false);
        btnadd.setVisible(false);
        lblplayerdetails.setVisible(false);
        lblplayername.setVisible(false);
        lblplayerteam.setVisible(false);
        lblplayerscountry.setVisible(false);
        lblperformance.setVisible(false);
        lblspeed.setVisible(false);
        lblstamina.setVisible(false);
        lblshotsontarget.setVisible(false);
        cbstamina.setVisible(false);
        lblplayerstats.setVisible(false);
        playerdetails.setVisible(false);
        enterplayer.setVisible(true);
        btnenter.setVisible(false);
        tfid.setVisible(false);
        tfname.setVisible(false);
        lblname.setVisible(false);
        lblid.setVisible(false);
        lbluserdetails.setVisible(false);
//        
//        File f = new file ("output.dat");
//        FileReader fr = new FileReader (f);
//        try (BufferedReader br = new BufferedReader(fr));
//        
//        try {
//            while{
//                (BufferedReader br = br.)
//            }
//        }
        
    }//GEN-LAST:event_playerdetailsActionPerformed

    private void enterplayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterplayerActionPerformed
        // TODO add your handling code here:
        lblplayerdetails.setVisible(true);
        lblplayername.setVisible(true);
        lblplayerteam.setVisible(true);
        lblplayerscountry.setVisible(true);
        tfplayername.setVisible(true);
        tfplayerteam.setVisible(true);
        tfpc.setVisible(true);
        btnadd.setVisible(false);
        add.setVisible(true);
        
    }//GEN-LAST:event_enterplayerActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        pdview.setVisible(false);
        adddetailsandstats.setVisible(true);
        add.setVisible(false);
        btnadd.setVisible(false);
        btnsave.setVisible(false);
        btnviewsaved.setVisible(false);
        redo.setVisible(false);
        
        
        
        
        lblplayerstats.setVisible(true);
        lblperformance.setVisible(true);
        lblspeed.setVisible(true);
        lblstamina.setVisible(true);
        lblshotsontarget.setVisible(true);
        cbperformance.setVisible(true);
        cbspeed.setVisible(true);
        cbstamina.setVisible(true);
        cbshotsontarget.setVisible(true);
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void cbperformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbperformanceActionPerformed
        // TODO add your handling code here:
        s = new Stats();
        if(cbperformance.getSelectedItem().equals("Great")){
            s.setPerformance(String.valueOf(cbperformance.getSelectedItem()));
        }
        else if(cbperformance.getSelectedItem().equals("Average")){
            s.setPerformance(String.valueOf(cbperformance.getSelectedItem()));
        }
        else{
            s.setPerformance(String.valueOf(cbperformance.getSelectedItem()));
        }
    }//GEN-LAST:event_cbperformanceActionPerformed

    private void cbspeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbspeedActionPerformed
        // TODO add your handling code here:
        if(cbspeed.getSelectedItem().equals("Great")){
            s.setSpeed(String.valueOf(cbspeed.getSelectedItem()));
        }
        else if(cbspeed.getSelectedItem().equals("Average")){
            s.setSpeed(String.valueOf(cbspeed.getSelectedItem()));
        }
        else{
            s.setSpeed(String.valueOf(cbspeed.getSelectedItem()));
        }
        
    }//GEN-LAST:event_cbspeedActionPerformed

    private void cbstaminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstaminaActionPerformed
        // TODO add your handling code here:
        if(cbstamina.getSelectedItem().equals("Great")){
            s.setStamina(String.valueOf(cbstamina.getSelectedItem()));
        }
        else if(cbstamina.getSelectedItem().equals("Average")){
            s.setStamina(String.valueOf(cbstamina.getSelectedItem()));
        }
        else{
            s.setStamina(String.valueOf(cbstamina.getSelectedItem()));
        }
    }//GEN-LAST:event_cbstaminaActionPerformed

    private void cbshotsontargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbshotsontargetActionPerformed
        // TODO add your handling code here:
        if(cbshotsontarget.getSelectedItem().equals("Great")){
            s.setShotsOnTarget(String.valueOf(cbshotsontarget.getSelectedItem()));
        }
        else if(cbshotsontarget.getSelectedItem().equals("Average")){
            s.setShotsOnTarget(String.valueOf(cbshotsontarget.getSelectedItem()));
        }
        else{
            s.setShotsOnTarget(String.valueOf(cbshotsontarget.getSelectedItem()));
        }
    }//GEN-LAST:event_cbshotsontargetActionPerformed

    private void adddetailsandstatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddetailsandstatsActionPerformed
        // TODO add your handling code here:
        
        
       
        btnview.setVisible(true);
        pdview.setVisible(false);
        redo.setVisible(true);
        if(s instanceof Stats){
            s.getPerformance();
            s.getSpeed();
            s.getStamina();
            s.getShotsOnTarget();
            
            
            
            
            
        }
        statsinfo.add(s);
        
        JOptionPane.showMessageDialog(null, "stats added");
    }//GEN-LAST:event_adddetailsandstatsActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        
        
        
        if(s instanceof Stats){
            JOptionPane.showMessageDialog(null, "Performance :" + s.getPerformance()+ "Speed :"+ s.getSpeed()+ "Stamina :"+ s.getStamina()+ "Shots on target :"+ s.getShotsOnTarget());
        }
        else{
            JOptionPane.showMessageDialog(null, "Performance :" + s.getPerformance()+ "Speed :"+ s.getSpeed()+ "Stamina :"+ s.getStamina()+ "Shots on target :"+ s.getShotsOnTarget());
        }
    }//GEN-LAST:event_btnviewActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        btnadd.setVisible(false);
        btnsave.setVisible(false);
        pdview.setVisible(true);
        redo.setVisible(false);
        
        playername = tfplayername.getText();
        playerage = tfplayerteam.getText();
        playercountry = tfpc.getText();
        
        Player a = new Player();
        a.setPlayername(playername);
        a.setPlayerage(playerage);
        a.setPlayercountry(playercountry);
        
        aList.add(a);
        
        count++;
        
        
    }//GEN-LAST:event_addActionPerformed

    private void pdviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdviewActionPerformed
        // TODO add your handling code here:
        btnsave.setVisible(true);
        
        
        for(int i = 0; i < aList.size();i++){
            JOptionPane.showMessageDialog(null, "Name : "+ aList.get(i).getPlayername()+"\n Age : "+ aList.get(i).getPlayerage()+ "\n Player Country : "+ aList.get(i).getPlayercountry());
            
        }
        
        
        
        
//        for (Stats i : statsinfo){
//            if(i instanceof Player){
//                JOptionPane.showMessageDialog(null, "Player name: " + ((Player) (i)).getPlayername()+ "Player age: " + ((Player) (i)).getPlayerage()+ "Player country: " + ((Player) (i)).getPlayercountry());
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Player name: " + ((Player) (i)).getPlayername()+ "Player age: " + ((Player) (i)).getPlayerage()+ "Player country: " + ((Player) (i)).getPlayercountry());
//
//            }
//            
//        }
        
        
    }//GEN-LAST:event_pdviewActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        // TODO add your handling code here:
        FantasyFootballGUI_1 f = new FantasyFootballGUI_1();
        
        f.setVisible(true);
    }//GEN-LAST:event_redoActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        btnviewsaved.setVisible(true);
        
        
        playername = tfplayername.getText();
        playerage = tfplayerteam.getText();
        playercountry = tfpc.getText();
        
        Player a = new Player();
        a.setPlayername(playername);
        a.setPlayerage(playerage);
        a.setPlayercountry(playercountry);
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("output.dat");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(a);
            
            JOptionPane.showMessageDialog(null, "File written");
            
            oStream.close();
            
        }
        catch(IOException e){
            System.out.println(e);
        }
        
        
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnviewsavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewsavedActionPerformed
        // TODO add your handling code here:
        
        btnadd.setVisible(true);
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("output.dat");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            Player x;
            x = (Player)oStream.readObject();
            
            JOptionPane.showMessageDialog(null, "Name : "+x.getPlayername()+ "Age : "+x.getPlayerage()+ "Country : "+x.getPlayercountry());
            
            oStream.close();
            
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
        
                
    }//GEN-LAST:event_btnviewsavedActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        Login Login  = new   Login ();
        Login .setVisible(true);
        
        
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FantasyFootballGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FantasyFootballGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FantasyFootballGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FantasyFootballGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FantasyFootballGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton adddetailsandstats;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnview;
    private javax.swing.JButton btnviewsaved;
    private javax.swing.JComboBox<String> cbperformance;
    private javax.swing.JComboBox<String> cbshotsontarget;
    private javax.swing.JComboBox<String> cbspeed;
    private javax.swing.JComboBox<String> cbstamina;
    private javax.swing.JButton enterplayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblperformance;
    private javax.swing.JLabel lblplayerdetails;
    private javax.swing.JLabel lblplayername;
    private javax.swing.JLabel lblplayerscountry;
    private javax.swing.JLabel lblplayerstats;
    private javax.swing.JLabel lblplayerteam;
    private javax.swing.JLabel lblshotsontarget;
    private javax.swing.JLabel lblspeed;
    private javax.swing.JLabel lblstamina;
    private javax.swing.JLabel lbluserdetails;
    private javax.swing.JButton pdview;
    private javax.swing.JButton playerdetails;
    private javax.swing.JButton redo;
    private fantasyfootball.Stats stats1;
    private fantasyfootball.Stats stats2;
    private fantasyfootball.Stats stats3;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfpc;
    private javax.swing.JTextField tfplayername;
    private javax.swing.JTextField tfplayerteam;
    // End of variables declaration//GEN-END:variables
}
//Designed by Brian Kelly and coded by Brian Kelly & Adam Cahill